//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebsite.Mvc3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleWebsite.Mvc3.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To.
        /// </summary>
        public static string AddTo {
            get {
                return ResourceManager.GetString("AddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Account.
        /// </summary>
        public static string ApproveAccount {
            get {
                return ResourceManager.GetString("ApproveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments: .
        /// </summary>
        public static string CommentsLabel {
            get {
                return ResourceManager.GetString("CommentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: .
        /// </summary>
        public static string CreatedLabel {
            get {
                return ResourceManager.GetString("CreatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days..
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disapprove Account.
        /// </summary>
        public static string DisapproveAccount {
            get {
                return ResourceManager.GetString("DisapproveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address: .
        /// </summary>
        public static string EmailAddressLabel {
            get {
                return ResourceManager.GetString("EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address &amp; Comments.
        /// </summary>
        public static string EmailAndComments {
            get {
                return ResourceManager.GetString("EmailAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a User.
        /// </summary>
        public static string FindAUser {
            get {
                return ResourceManager.GetString("FindAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours..
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Roles.
        /// </summary>
        public static string InitialRoles {
            get {
                return ResourceManager.GetString("InitialRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Active:.
        /// </summary>
        public static string LastActiveLabel {
            get {
                return ResourceManager.GetString("LastActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed:.
        /// </summary>
        public static string LastChangedLabel {
            get {
                return ResourceManager.GetString("LastChangedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login: .
        /// </summary>
        public static string LastLoginLabel {
            get {
                return ResourceManager.GetString("LastLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out since.
        /// </summary>
        public static string LockedOutSince {
            get {
                return ResourceManager.GetString("LockedOutSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes..
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password question defined..
        /// </summary>
        public static string NoPasswordQuestionDefined {
            get {
                return ResourceManager.GetString("NoPasswordQuestionDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles have been created..
        /// </summary>
        public static string NoRolesHaveBeenCreated {
            get {
                return ResourceManager.GetString("NoRolesHaveBeenCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users are in this role..
        /// </summary>
        public static string NoUsersAreInThisRole {
            get {
                return ResourceManager.GetString("NoUsersAreInThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users have registered..
        /// </summary>
        public static string NoUsersHaveRegistered {
            get {
                return ResourceManager.GetString("NoUsersHaveRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline for.
        /// </summary>
        public static string OfflineFor {
            get {
                return ResourceManager.GetString("OfflineFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day..
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour..
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute..
        /// </summary>
        public static string OneMinute {
            get {
                return ResourceManager.GetString("OneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; First.
        /// </summary>
        public static string PagedListFirst {
            get {
                return ResourceManager.GetString("PagedListFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &gt;&gt;.
        /// </summary>
        public static string PagedListLast {
            get {
                return ResourceManager.GetString("PagedListLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string PagedListNext {
            get {
                return ResourceManager.GetString("PagedListNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Last.
        /// </summary>
        public static string PagedListPrevious {
            get {
                return ResourceManager.GetString("PagedListPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Again...).
        /// </summary>
        public static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Answer:.
        /// </summary>
        public static string PasswordAnswerLabel {
            get {
                return ResourceManager.GetString("PasswordAnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Question:.
        /// </summary>
        public static string PasswordQuestionLabel {
            get {
                return ResourceManager.GetString("PasswordQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From.
        /// </summary>
        public static string RemoveFrom {
            get {
                return ResourceManager.GetString("RemoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Random Password and Email User.
        /// </summary>
        public static string ResetToRandomPasswordAndEmailUser {
            get {
                return ResourceManager.GetString("ResetToRandomPasswordAndEmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role: .
        /// </summary>
        public static string RoleLabel {
            get {
                return ResourceManager.GetString("RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Email Address and Comments.
        /// </summary>
        public static string SaveEmailAddressAndComments {
            get {
                return ResourceManager.GetString("SaveEmailAddressAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Answer.
        /// </summary>
        public static string SecretAnswer {
            get {
                return ResourceManager.GetString("SecretAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Question.
        /// </summary>
        public static string SecretQuestion {
            get {
                return ResourceManager.GetString("SecretQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        public static string Unapproved {
            get {
                return ResourceManager.GetString("Unapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status.
        /// </summary>
        public static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Account.
        /// </summary>
        public static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Administration.
        /// </summary>
        public static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details: .
        /// </summary>
        public static string UserDetailsLabel {
            get {
                return ResourceManager.GetString("UserDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: .
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Email Address:.
        /// </summary>
        public static string UsernameOrEmailAddressLabel {
            get {
                return ResourceManager.GetString("UsernameOrEmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;lt;roleManager enabled=&quot;false&quot;&amp;gt; to &amp;lt;roleManager enabled=&quot;true&quot;&amp;gt; in your web.config file..
        /// </summary>
        public static string WarningChangeRoleManager {
            get {
                return ResourceManager.GetString("WarningChangeRoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Your Role Provider is currently disabled - any user may currently visit this page..
        /// </summary>
        public static string WarningRoleProviderDisabled {
            get {
                return ResourceManager.GetString("WarningRoleProviderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must confirm your password..
        /// </summary>
        public static string YouMustConfirmPassword {
            get {
                return ResourceManager.GetString("YouMustConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify an email address..
        /// </summary>
        public static string YouMustSpecifiyEmailAddress {
            get {
                return ResourceManager.GetString("YouMustSpecifiyEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a password..
        /// </summary>
        public static string YouMustSpecifyPassword {
            get {
                return ResourceManager.GetString("YouMustSpecifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a username..
        /// </summary>
        public static string YouMustSpecifyUsername {
            get {
                return ResourceManager.GetString("YouMustSpecifyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Password.
        /// </summary>
        public static string YourNewPassword {
            get {
                return ResourceManager.GetString("YourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password is: .
        /// </summary>
        public static string YourNewPasswordIsLabel {
            get {
                return ResourceManager.GetString("YourNewPasswordIsLabel", resourceCulture);
            }
        }
    }
}
